### ISSUE TITLE
API no longer active

### ISSUE THREAD

**Issue by mrwhale** [andrewda/hltv-live-games#9]
Was trying to use this to watch for when matches go live, so I could automatically start a `hltv-livescore` but I was getting a strange error. I've looked at the URL you are requesting to get the data and it seems that it is no longer active

**Comment by andrewda** [comment]
Yep, saw that a couple weeks ago. Either we'll need to find the new API end point or scrape HLTV.

**Comment by andrewda** [comment]
Sorry this took a while – newest version should fix it.
